# Generated by Django 4.2 on 2025-12-06 17:06

from django.db import migrations, models
import transcribe_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=transcribe_app.models.upload_to),
        ),
    ]
